#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

echo " =========================================================== "
echo "   Trying to build project before committing...              "
echo " =========================================================== "

make clean
make

if [[ $? != 0 ]]; then
	echo " =========================================================== "
	echo "   Pre-commit Build FAILED                                   "
	echo " =========================================================== "
	exit 1
else
	echo " =========================================================== "
	echo "   Pre-commit Build SUCCESSFUL                               "
	echo " =========================================================== "
	exit 0
fi
