#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Test clang-format  
clangformatout=$(git clang-format --diff --staged -q)  
  
if [ "$clangformatout" != "" ]  
then
	exec 1>&2
    echo "Format ERROR!"
	echo ""
    echo "The new code that is added contains differences against"
	echo "clang-format rules. Please run git clang-format to fix this before"
	echo "doing a commit."
	echo ""
    exit 1
fi

# Test if project builds without any errors
make clean
make

if [[ $? != 0 ]]; then
	exec 1>&2
	echo "Build FAILED!"
	echo ""
	echo "Project could not build successfully. Please fix errors first."
	exit 1
fi
