#!/bin/sh

log_file=logfile

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Test clang-format to check for wrong formatting
clangformatout=$(git clang-format --diff --staged -q)  
  
if [ "$clangformatout" != "" ]  
then
	exec 1>&2
    echo "Format ERROR!"
	echo ""
    echo "The new code that is added contains differences against"
	echo "clang-format rules. Please run git clang-format to fix this before"
	echo "doing a commit."
	echo ""
    exit 1
fi

# Test if project builds without any errors
makeclean=$(make clean)
make >&$log_file
makeout=$?

results=$(cat $log_file)
rm $log_file

if [[ $makeout != 0 ]]; then
	exec 1>&2
	echo "Build FAILED!"
	echo ""
	echo "Project could not build successfully. Please fix errors first."
	echo ""
	echo "$results"
	exit 1
fi
