name: main-workflow

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-hex:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: build hex file
        run:  docker compose run --rm build-hex
      - name: upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: hex-file
          path: output/exe/card-ecg.hex
  complexity-check:
    runs-on: ubuntu-latest
    needs: build-hex # project has to build successfully before complexity check
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: run complexity check
        run:  docker compose run --rm complexity-check
  cppcheck:
    runs-on: ubuntu-latest
    needs: build-hex # project has to build successfully before static analysis
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: run cppcheck
        run:  docker compose run --rm cppcheck
  clang-tidy:
    runs-on: ubuntu-latest
    needs: build-hex # project has to build successfully before static analysis
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: run clang-tidy
        run:  docker compose run --rm clang-tidy
  unit-tests:
    runs-on: ubuntu-latest
    needs: build-hex # project has to build successfully before unit tests
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: run unit tests
        run:  docker compose run --rm unit-tests
